package com.melody.model;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class Singer {
    private Long singerId;
    private String singerName;
    private String singerPhoto;
    private String singerInfo;
    private String singerHashtags;

    public Singer(String singerName, String singerPhoto, String singerInfo, String singerHashtags) {
        // Omitting singerId in the constructor as it will be generated by the database.
        this.singerName = singerName;
        this.singerPhoto = singerPhoto;
        this.singerInfo = singerInfo;
        this.singerHashtags = singerHashtags;
    }
}
